-- 2025 
-- 1st Round Picks
INSERT INTO Assets (round, year, original_team_id, current_team_id) VALUES
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Nashville Predators'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Colorado Avalanche'), (SELECT team_id FROM Teams WHERE team_name='Colorado Avalanche')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks'), (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres'), (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings'), (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers'), (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers'), (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Vancouver Canucks'), (SELECT team_id FROM Teams WHERE team_name='Vancouver Canucks')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Islanders'), (SELECT team_id FROM Teams WHERE team_name='New York Islanders')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes'), (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Ottawa Senators'), (SELECT team_id FROM Teams WHERE team_name='Ottawa Senators')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets'), (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks'), (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='St. Louis Blues'), (SELECT team_id FROM Teams WHERE team_name='St. Louis Blues')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Los Angeles Kings'), (SELECT team_id FROM Teams WHERE team_name='Los Angeles Kings')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Florida Panthers'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken'), (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins'), (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Boston Bruins'), (SELECT team_id FROM Teams WHERE team_name='Boston Bruins')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks'), (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Washington Capitals'), (SELECT team_id FROM Teams WHERE team_name='Washington Capitals')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club'), (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils'), (SELECT team_id FROM Teams WHERE team_name='Calgary Flames')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Minnesota Wild'), (SELECT team_id FROM Teams WHERE team_name='Minnesota Wild')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Toronto Maple Leafs'), (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Dallas Stars'), (SELECT team_id FROM Teams WHERE team_name='Dallas Stars')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Rangers'), (SELECT team_id FROM Teams WHERE team_name='New York Rangers')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Winnipeg Jets'), (SELECT team_id FROM Teams WHERE team_name='Winnipeg Jets')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Tampa Bay Lightning'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(1, 2025, (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'), (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'));

-- 2nd Round Picks
INSERT INTO Assets (round, year, original_team_id, current_team_id) VALUES
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Nashville Predators'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Colorado Avalanche'), (SELECT team_id FROM Teams WHERE team_name='Calgary Flames')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks'), (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres'), (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings'), (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers'), (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers'), (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Vancouver Canucks'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Islanders'), (SELECT team_id FROM Teams WHERE team_name='New York Islanders')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes'), (SELECT team_id FROM Teams WHERE team_name='Washington Capitals')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Ottawa Senators'), (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets'), (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers'), (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks'), (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='St. Louis Blues'), (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Los Angeles Kings'), (SELECT team_id FROM Teams WHERE team_name='Tampa Bay Lightning')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Florida Panthers'), (SELECT team_id FROM Teams WHERE team_name='Toronto Maple Leafs')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken'), (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Boston Bruins'), (SELECT team_id FROM Teams WHERE team_name='Washington Capitals')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights'), (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks'), (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Washington Capitals'), (SELECT team_id FROM Teams WHERE team_name='Washington Capitals')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club'), (SELECT team_id FROM Teams WHERE team_name='Tampa Bay Lightning')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils'), (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Minnesota Wild'), (SELECT team_id FROM Teams WHERE team_name='Minnesota Wild')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Toronto Maple Leafs'), (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Dallas Stars'), (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Rangers'), (SELECT team_id FROM Teams WHERE team_name='Colorado Avalanche')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Winnipeg Jets'), (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Tampa Bay Lightning'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(2, 2025, (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'), (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'));

-- 3rd Round Picks
INSERT INTO Assets (round, year, original_team_id, current_team_id) VALUES
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Nashville Predators'), (SELECT team_id FROM Teams WHERE team_name='Nashville Predators')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Colorado Avalanche'), (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks'), (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres'), (SELECT team_id FROM Teams WHERE team_name='Buffalo Sabres')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings'), (SELECT team_id FROM Teams WHERE team_name='Detroit Red Wings')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers'), (SELECT team_id FROM Teams WHERE team_name='Philadelphia Flyers')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers'), (SELECT team_id FROM Teams WHERE team_name='San Jose Sharks')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Vancouver Canucks'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Islanders'), (SELECT team_id FROM Teams WHERE team_name='New York Islanders')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes'), (SELECT team_id FROM Teams WHERE team_name='Washington Capitals')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Ottawa Senators'), (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets'), (SELECT team_id FROM Teams WHERE team_name='Columbus Blue Jackets')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Chicago Blackhawks'), (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='St. Louis Blues'), (SELECT team_id FROM Teams WHERE team_name='Edmonton Oilers')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Los Angeles Kings'), (SELECT team_id FROM Teams WHERE team_name='Los Angeles Kings')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Florida Panthers'), (SELECT team_id FROM Teams WHERE team_name='Ottawa Senators')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken'), (SELECT team_id FROM Teams WHERE team_name='Seattle Kraken')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins'), (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Boston Bruins'), (SELECT team_id FROM Teams WHERE team_name='Boston Bruins')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights'), (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks'), (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Washington Capitals'), (SELECT team_id FROM Teams WHERE team_name='Vegas Golden Knights')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club'), (SELECT team_id FROM Teams WHERE team_name='Utah Hockey Club')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='New Jersey Devils'), (SELECT team_id FROM Teams WHERE team_name='Montréal Canadiens')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Minnesota Wild'), (SELECT team_id FROM Teams WHERE team_name='Pittsburgh Penguins')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Toronto Maple Leafs'), (SELECT team_id FROM Teams WHERE team_name='Anaheim Ducks')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Dallas Stars'), (SELECT team_id FROM Teams WHERE team_name='Dallas Stars')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='New York Rangers'), (SELECT team_id FROM Teams WHERE team_name='New York Rangers')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Winnipeg Jets'), (SELECT team_id FROM Teams WHERE team_name='Winnipeg Jets')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Tampa Bay Lightning'), (SELECT team_id FROM Teams WHERE team_name='Carolina Hurricanes')),
(3, 2025, (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'), (SELECT team_id FROM Teams WHERE team_name='Calgary Flames'));